### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by konsumlamm** [gifnksm/polynomial-rs#9]
@gifnksm this project looks pretty abandoned (last activity was 2018), are you still interested in maintaining it?

**Comment by gifnksm** [comment]
I am not currently using this library and have no motivation to actively update it at this time. Sorry.

**Comment by konsumlamm** [comment]
Would you be open to appoint a co-maintainer and/or actively merge PRs? If so, I'd be definitely interested in contributing!

**Comment by gifnksm** [comment]
I will review and merge the PRs as soon as possible .
If you do not receive a reply from me, please mention me.
